import type { Metadata } from "next";

import { AuthFloatingPanel } from "@/components/shared/auth-floating-panel";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthFloatingPanel />
        {children}
      </body>
    </html>
  );
}
