-- ThinkerTools Quests: seed Contradiction Spotting launch rounds into quests_activities.
-- Source: ThinkerTools Re-design - contradiction spotting launch content pack.docx

set search_path = public;

with target_skill as (
  select id
  from public.quests_skills
  where slug = 'philosophical-reasoning'
  limit 1
), authored_rounds (
  slug,
  title,
  template_family,
  short_description,
  difficulty_label,
  completion_criteria,
  xp_reward,
  recommended_level_min,
  recommended_level_max,
  round_type,
  round_code,
  question_text,
  correct_label_1,
  correct_label_2,
  explanation,
  claim_a,
  claim_b,
  claim_c,
  claim_d
) as (
values
  ('philo-contradiction-dcc-01', 'Contradiction Spotting: DCC-01', 'contradiction_direct_claim_conflict', 'Identify the strongest contradiction between labeled claims.', 'intro', 'Select the two labels that are in strongest contradiction.', 10, 1, 3, 'drill_standard', 'DCC-01', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A says truth-telling should always happen. Claim B says there are cases where lying is morally required. Both cannot remain true without qualification.', 'A. People should always tell the truth.', 'B. Sometimes lying is morally necessary.', 'C. Honesty helps social trust.', 'D. Trust matters in human communities.'),
  ('philo-contradiction-dcc-02', 'Contradiction Spotting: DCC-02', 'contradiction_direct_claim_conflict', 'Identify the strongest contradiction between labeled claims.', 'intro', 'Select the two labels that are in strongest contradiction.', 10, 1, 3, 'drill_standard', 'DCC-02', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A grants universal freedom of expression. Claim B denies that freedom to at least some opinions. They conflict directly.', 'A. Everyone deserves equal freedom of expression.', 'B. Some opinions should never be allowed to be expressed.', 'C. Speech can cause harm.', 'D. Public discussion shapes society.'),
  ('philo-contradiction-dcc-03', 'Contradiction Spotting: DCC-03', 'contradiction_direct_claim_conflict', 'Identify the strongest contradiction between labeled claims.', 'intro', 'Select the two labels that are in strongest contradiction.', 10, 1, 3, 'drill_standard', 'DCC-03', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A says rules never admit exceptions. Claim B says emergencies can justify breaking them.', 'A. Rules should always be followed.', 'B. Some emergencies justify breaking rules.', 'C. Rules help people coordinate.', 'D. Emergencies create unusual pressure.'),
  ('philo-contradiction-dcc-04', 'Contradiction Spotting: DCC-04', 'contradiction_direct_claim_conflict', 'Identify the strongest contradiction between labeled claims.', 'intro', 'Select the two labels that are in strongest contradiction.', 10, 1, 3, 'drill_standard', 'DCC-04', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A says moral truth is universal. Claim B says moral truth varies by culture. Those positions conflict directly.', 'A. Moral truth is the same for everyone.', 'B. Moral truth changes from culture to culture.', 'C. People grow up inside different moral systems.', 'D. Culture influences judgment.'),
  ('philo-contradiction-dcc-05', 'Contradiction Spotting: DCC-05', 'contradiction_direct_claim_conflict', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 2, 4, 'drill_standard', 'DCC-05', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A assumes meaningful responsibility for choices. Claim B denies genuine alternatives. That creates direct tension.', 'A. People are fully responsible for their choices.', 'B. No one could ever have acted differently than they did.', 'C. Circumstances shape behavior.', 'D. Responsibility matters for justice.'),
  ('philo-contradiction-dcc-06', 'Contradiction Spotting: DCC-06', 'contradiction_direct_claim_conflict', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 2, 4, 'drill_standard', 'DCC-06', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A restricts knowledge entirely to experience. Claim B says at least some truths do not require experience.', 'A. Knowledge comes only from experience.', 'B. Some truths can be known without experience.', 'C. Experience teaches us about the world.', 'D. Some people trust reason more than observation.'),
  ('philo-contradiction-dcc-07', 'Contradiction Spotting: DCC-07', 'contradiction_direct_claim_conflict', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 2, 4, 'drill_standard', 'DCC-07', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A denies major change in identity. Claim B allows fundamental transformation. They are directly opposed.', 'A. Personal identity never changes.', 'B. A person can become fundamentally different over time.', 'C. People often change beliefs and habits.', 'D. Continuity matters to identity.'),
  ('philo-contradiction-dcc-08', 'Contradiction Spotting: DCC-08', 'contradiction_direct_claim_conflict', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'DCC-08', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A says all action is selfish. Claim B says at least some actions are not selfish in that way.', 'A. Every action is selfish at its core.', 'B. Some actions are genuinely altruistic.', 'C. Motives can be mixed.', 'D. Helping others can feel rewarding.'),
  ('philo-contradiction-dcc-09', 'Contradiction Spotting: DCC-09', 'contradiction_direct_claim_conflict', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 20, 4, 6, 'drill_higher_authoring', 'DCC-09', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A points toward consistency across similar cases. Claim B opens room for exception-making. The tension becomes more meaningful because both principles have moral force.', 'A. Justice requires treating like cases alike.', 'B. Mercy sometimes requires making exceptions for special hardship.', 'C. Hardship can affect what fairness demands.', 'D. Justice should not be arbitrary.'),
  ('philo-contradiction-dcc-10', 'Contradiction Spotting: DCC-10', 'contradiction_direct_claim_conflict', 'Identify the strongest contradiction between labeled claims.', 'advanced', 'Select the two labels that are in strongest contradiction.', 20, 5, 7, 'drill_higher_authoring', 'DCC-10', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A emphasizes non-interference as freedom. Claim B accepts limiting freedom when choices are judged irrational. That is the core contradiction.', 'A. Freedom means individuals should choose without interference.', 'B. A good society should prevent people from making deeply irrational choices.', 'C. Some choices damage the chooser.', 'D. Interference can undermine autonomy.'),
  ('philo-contradiction-rve-01', 'Contradiction Spotting: RVE-01', 'contradiction_rule_versus_exception', 'Identify the strongest contradiction between labeled claims.', 'intro', 'Select the two labels that are in strongest contradiction.', 10, 1, 3, 'drill_standard', 'RVE-01', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A denies all exceptions to stealing. Claim B allows one in an emergency case.', 'A. Stealing is always wrong.', 'B. Taking medicine to save a dying person is justified.', 'C. Medicine is someone else’s property.', 'D. Emergencies are morally serious.'),
  ('philo-contradiction-rve-02', 'Contradiction Spotting: RVE-02', 'contradiction_rule_versus_exception', 'Identify the strongest contradiction between labeled claims.', 'intro', 'Select the two labels that are in strongest contradiction.', 10, 1, 3, 'drill_standard', 'RVE-02', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A says promises admit no exceptions. Claim B explicitly allows one under severe harm.', 'A. Promises must always be kept.', 'B. Breaking a promise is acceptable if keeping it would cause severe harm.', 'C. Promises create trust.', 'D. Harm prevention matters morally.'),
  ('philo-contradiction-rve-03', 'Contradiction Spotting: RVE-03', 'contradiction_rule_versus_exception', 'Identify the strongest contradiction between labeled claims.', 'intro', 'Select the two labels that are in strongest contradiction.', 10, 1, 3, 'drill_standard', 'RVE-03', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A rejects exceptions in application. Claim B allows exceptions when justice demands them.', 'A. The law should be applied exactly as written.', 'B. Judges should make exceptions when the outcome would be cruel.', 'C. Laws aim at public order.', 'D. Cruelty can be morally relevant.'),
  ('philo-contradiction-rve-04', 'Contradiction Spotting: RVE-04', 'contradiction_rule_versus_exception', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 2, 4, 'drill_standard', 'RVE-04', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A allows no exception. Claim B allows one when the system is unjust.', 'A. Academic cheating is always unacceptable.', 'B. Using prohibited help is justified if the grading system is unfair.', 'C. Fairness matters in evaluation.', 'D. Cheating undermines trust.'),
  ('philo-contradiction-rve-05', 'Contradiction Spotting: RVE-05', 'contradiction_rule_versus_exception', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 2, 4, 'drill_standard', 'RVE-05', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A says privacy is exceptionless. Claim B permits overriding it in at least one case.', 'A. Privacy should never be violated.', 'B. Privacy may be overridden to stop immediate violence.', 'C. Privacy protects dignity.', 'D. Safety can justify emergency action.'),
  ('philo-contradiction-rve-06', 'Contradiction Spotting: RVE-06', 'contradiction_rule_versus_exception', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 2, 4, 'drill_standard', 'RVE-06', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A requires obedience in all cases. Claim B permits disobedience in at least some cases.', 'A. Citizens should always obey the state.', 'B. Civil disobedience can be justified under oppression.', 'C. States maintain order.', 'D. Oppression can corrupt authority.'),
  ('philo-contradiction-rve-07', 'Contradiction Spotting: RVE-07', 'contradiction_rule_versus_exception', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'RVE-07', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A makes loyalty exceptionless. Claim B introduces a serious-harm exception.', 'A. A friend should always be defended publicly.', 'B. A friend should be criticized publicly if they are causing serious harm.', 'C. Loyalty matters in friendship.', 'D. Public harm may require public response.'),
  ('philo-contradiction-rve-08', 'Contradiction Spotting: RVE-08', 'contradiction_rule_versus_exception', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'RVE-08', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A bans deception absolutely. Claim B permits it in a murder-prevention case.', 'A. One should never deceive another person.', 'B. Deception is allowed when it prevents a murder.', 'C. Deception damages trust.', 'D. Saving innocent life has moral weight.'),
  ('philo-contradiction-rve-09', 'Contradiction Spotting: RVE-09', 'contradiction_rule_versus_exception', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 20, 4, 6, 'drill_higher_authoring', 'RVE-09', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A rejects exceptions entirely. Claim B says good institutions should build them in under extreme conditions.', 'A. Public institutions should never favor one case over another.', 'B. Institutions should create emergency exceptions for catastrophic circumstances.', 'C. Equal treatment supports legitimacy.', 'D. Catastrophic cases may require flexible response.'),
  ('philo-contradiction-rve-10', 'Contradiction Spotting: RVE-10', 'contradiction_rule_versus_exception', 'Identify the strongest contradiction between labeled claims.', 'advanced', 'Select the two labels that are in strongest contradiction.', 20, 5, 7, 'drill_higher_authoring', 'RVE-10', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A says exceptions weaken moral rules. Claim B says some exceptions actually improve coherence.', 'A. Moral rules lose authority if they allow exceptions.', 'B. Moral rules are more coherent when they specify narrow exceptions.', 'C. Coherence matters to moral guidance.', 'D. Vague rules create confusion.'),
  ('philo-contradiction-pva-01', 'Contradiction Spotting: PVA-01', 'contradiction_principle_versus_action', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 2, 4, 'drill_standard', 'PVA-01', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A protects belief freedom broadly. Claim B withdraws it from certain beliefs.', 'A. Everyone should be free to form their own beliefs.', 'B. People with irrational beliefs should not be allowed to hold them.', 'C. Belief freedom matters in a plural society.', 'D. Irrational beliefs can be socially dangerous.'),
  ('philo-contradiction-pva-02', 'Contradiction Spotting: PVA-02', 'contradiction_principle_versus_action', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 2, 4, 'drill_standard', 'PVA-02', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A commits to equal treatment. Claim B recommends unequal allocation on achievement grounds.', 'A. All students deserve equal treatment.', 'B. Stronger students should receive more teacher attention because they can achieve more.', 'C. Teacher time is limited.', 'D. Equality is often difficult in practice.'),
  ('philo-contradiction-pva-03', 'Contradiction Spotting: PVA-03', 'contradiction_principle_versus_action', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 2, 4, 'drill_standard', 'PVA-03', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A praises transparency as a leadership principle. Claim B recommends secrecy for important decisions.', 'A. Leadership should be transparent.', 'B. Important decisions should often be hidden from the public.', 'C. Some information can be destabilizing.', 'D. Trust often depends on openness.'),
  ('philo-contradiction-pva-04', 'Contradiction Spotting: PVA-04', 'contradiction_principle_versus_action', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'PVA-04', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A rejects status-based judgment. Claim B explicitly endorses it.', 'A. People should be judged by their actions, not their status.', 'B. Some people deserve special treatment because of who they are.', 'C. Status can influence social institutions.', 'D. Fairness often resists favoritism.'),
  ('philo-contradiction-pva-05', 'Contradiction Spotting: PVA-05', 'contradiction_principle_versus_action', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'PVA-05', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A says reward should track effort. Claim B lets birth status override that principle.', 'A. Society should reward hard work.', 'B. Inheritance should determine access to the best opportunities.', 'C. Opportunity shapes outcomes.', 'D. Hard work can matter without being the only factor.'),
  ('philo-contradiction-pva-06', 'Contradiction Spotting: PVA-06', 'contradiction_principle_versus_action', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'PVA-06', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A endorses independence. Claim B suppresses questioning that independence would involve.', 'A. People should be encouraged to think independently.', 'B. Schools should discourage students from questioning accepted views.', 'C. Social stability can be valuable.', 'D. Independent thought can challenge orthodoxy.'),
  ('philo-contradiction-pva-07', 'Contradiction Spotting: PVA-07', 'contradiction_principle_versus_action', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 4, 6, 'drill_standard', 'PVA-07', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A makes consent the basis of permissibility. Claim B permits exceptions without consent.', 'A. Consent is what makes intimate actions morally permissible.', 'B. Some intimate actions are acceptable even without valid consent if the intention is loving.', 'C. Intention can affect moral judgment.', 'D. Valid consent protects autonomy.'),
  ('philo-contradiction-pva-08', 'Contradiction Spotting: PVA-08', 'contradiction_principle_versus_action', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 4, 6, 'drill_standard', 'PVA-08', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A centers policy on shared benefit. Claim B centers it on existing power.', 'A. Public policy should serve the common good.', 'B. Policy should be designed mainly to benefit those already most powerful.', 'C. Power often shapes policy.', 'D. The common good can conflict with elite interests.'),
  ('philo-contradiction-pva-09', 'Contradiction Spotting: PVA-09', 'contradiction_principle_versus_action', 'Identify the strongest contradiction between labeled claims.', 'advanced', 'Select the two labels that are in strongest contradiction.', 20, 5, 7, 'drill_higher_authoring', 'PVA-09', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A resists using people merely as instruments. Claim B allows doing so when the welfare gains are large enough.', 'A. We should respect each person as an end in themselves.', 'B. It is acceptable to sacrifice a few innocent people whenever doing so increases total welfare enough.', 'C. Welfare matters morally.', 'D. Respect can constrain aggregation.'),
  ('philo-contradiction-pva-10', 'Contradiction Spotting: PVA-10', 'contradiction_principle_versus_action', 'Identify the strongest contradiction between labeled claims.', 'advanced', 'Select the two labels that are in strongest contradiction.', 20, 6, 8, 'drill_higher_authoring', 'PVA-10', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A treats equal voice as essential. Claim B proposes unequal political power.', 'A. Democratic authority depends on equal political voice.', 'B. More educated citizens should receive more votes.', 'C. Expertise may improve decisions.', 'D. Equal voice is central to democracy.'),
  ('philo-contradiction-uec-01', 'Contradiction Spotting: UEC-01', 'contradiction_universal_vs_edge_case', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'UEC-01', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A allows no exceptions. Claim B introduces one in a disaster case.', 'A. Moral rules never admit exceptions.', 'B. It is acceptable to break a rule to prevent a disaster.', 'C. Disasters carry unusual moral urgency.', 'D. Rules help guide action.'),
  ('philo-contradiction-uec-02', 'Contradiction Spotting: UEC-02', 'contradiction_universal_vs_edge_case', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'UEC-02', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A rejects punishment or coercive response entirely. Claim B allows at least one coercive case in defense of others.', 'A. Punishment is never justified.', 'B. It is acceptable to restrain a violent attacker to protect others.', 'C. Restraint limits liberty.', 'D. Protecting others can justify force.'),
  ('philo-contradiction-uec-03', 'Contradiction Spotting: UEC-03', 'contradiction_universal_vs_edge_case', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'UEC-03', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A rejects judgment in all cases. Claim B endorses institutional judgment under proof.', 'A. No one should ever judge another person.', 'B. A court should convict a murderer when guilt is proven.', 'C. Courts exist to judge conduct.', 'D. Some judgments are institutional rather than personal.'),
  ('philo-contradiction-uec-04', 'Contradiction Spotting: UEC-04', 'contradiction_universal_vs_edge_case', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 4, 6, 'drill_standard', 'UEC-04', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A treats desire as a reliable sign of the good. Claim B gives a case where strong desire points toward harm instead.', 'A. Desire always reveals what is good for a person.', 'B. Addictive cravings can be deeply harmful even when intensely desired.', 'C. Desire and flourishing can diverge.', 'D. People often want what harms them.'),
  ('philo-contradiction-uec-05', 'Contradiction Spotting: UEC-05', 'contradiction_universal_vs_edge_case', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 4, 6, 'drill_standard', 'UEC-05', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A says courage is admirable in every instance. Claim B says some seemingly courageous acts are not admirable at all.', 'A. Courage is always admirable.', 'B. Reckless refusal to retreat can be foolish rather than admirable.', 'C. Courage can resemble recklessness.', 'D. Context matters to virtue.'),
  ('philo-contradiction-uec-06', 'Contradiction Spotting: UEC-06', 'contradiction_universal_vs_edge_case', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 4, 6, 'drill_standard', 'UEC-06', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A says freedom always helps flourishing. Claim B presents an edge case where it undermines flourishing.', 'A. Freedom always increases human flourishing.', 'B. Some people become less capable of flourishing when offered unlimited choice.', 'C. Choice can overwhelm people.', 'D. Freedom often has value.'),
  ('philo-contradiction-uec-07', 'Contradiction Spotting: UEC-07', 'contradiction_universal_vs_edge_case', 'Identify the strongest contradiction between labeled claims.', 'advanced', 'Select the two labels that are in strongest contradiction.', 10, 5, 7, 'drill_standard', 'UEC-07', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A treats efficiency as always good. Claim B allows efficient systems to be morally bad.', 'A. Efficiency is always a sign of good institutions.', 'B. Some efficient institutions produce morally terrible outcomes.', 'C. Institutions can be efficient and unjust.', 'D. Efficiency is one dimension of performance.'),
  ('philo-contradiction-uec-08', 'Contradiction Spotting: UEC-08', 'contradiction_universal_vs_edge_case', 'Identify the strongest contradiction between labeled claims.', 'advanced', 'Select the two labels that are in strongest contradiction.', 10, 5, 7, 'drill_standard', 'UEC-08', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A universalizes the moral value of suffering. Claim B presents a case where suffering has no such effect.', 'A. Suffering always makes people morally better.', 'B. Some suffering degrades people without teaching them anything.', 'C. Hardship can sometimes strengthen people.', 'D. Not all pain is transformative.'),
  ('philo-contradiction-uec-09', 'Contradiction Spotting: UEC-09', 'contradiction_universal_vs_edge_case', 'Identify the strongest contradiction between labeled claims.', 'advanced', 'Select the two labels that are in strongest contradiction.', 20, 6, 8, 'drill_higher_authoring', 'UEC-09', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A treats tolerance as exceptionless. Claim B introduces a paradoxical edge case where unlimited tolerance defeats itself.', 'A. Tolerance is always a virtue.', 'B. A society should refuse to tolerate movements committed to destroying tolerance itself.', 'C. Tolerance can be self-undermining.', 'D. Virtues may need boundaries.'),
  ('philo-contradiction-uec-10', 'Contradiction Spotting: UEC-10', 'contradiction_universal_vs_edge_case', 'Identify the strongest contradiction between labeled claims.', 'advanced', 'Select the two labels that are in strongest contradiction.', 20, 7, 9, 'drill_higher_authoring', 'UEC-10', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A forbids tradeoffs involving dignity in all cases. Claim B introduces a catastrophic exception.', 'A. Human dignity can never be traded off for any social gain.', 'B. In rare catastrophic scenarios, sacrificing one person’s dignity may prevent mass destruction.', 'C. Catastrophic cases pressure moral rules.', 'D. Dignity often constrains policy.'),
  ('philo-contradiction-bip-01', 'Contradiction Spotting: BIP-01', 'contradiction_belief_set_incompatible_pair', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 2, 4, 'drill_standard', 'BIP-01', 'Which two claims are in strongest contradiction?', 'A', 'C', 'Claim A makes morality entirely culture-dependent. Claim C says at least some moral truths are culture-independent.', 'A. Moral rules are entirely shaped by culture.', 'B. Different cultures can have different moral norms.', 'C. Some actions are wrong no matter what any culture believes.', 'D. Culture influences how people reason.'),
  ('philo-contradiction-bip-02', 'Contradiction Spotting: BIP-02', 'contradiction_belief_set_incompatible_pair', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 2, 4, 'drill_standard', 'BIP-02', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A requires equal treatment under law. Claim B introduces a status-based exception.', 'A. People should be treated equally under the law.', 'B. Wealthy citizens should receive lighter punishments because they contribute more.', 'C. Law should be impartial.', 'D. Contributions to society matter morally.'),
  ('philo-contradiction-bip-03', 'Contradiction Spotting: BIP-03', 'contradiction_belief_set_incompatible_pair', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'BIP-03', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A ties freedom to self-choice. Claim B allows freedom to involve paternalistic restriction.', 'A. Freedom requires the ability to choose for oneself.', 'B. Genuine freedom sometimes requires being protected from one’s own choices.', 'C. Some choices are self-destructive.', 'D. Autonomy matters morally.'),
  ('philo-contradiction-bip-04', 'Contradiction Spotting: BIP-04', 'contradiction_belief_set_incompatible_pair', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'BIP-04', 'Which two claims are in strongest contradiction?', 'A', 'C', 'If people deserve credit only for what they control, and talent is mostly outside control, then heavily rewarding talent creates tension with that principle.', 'A. People deserve credit only for what they control.', 'B. Talent is mostly outside a person’s control.', 'C. Talent should be rewarded heavily.', 'D. Control matters to desert.'),
  ('philo-contradiction-bip-05', 'Contradiction Spotting: BIP-05', 'contradiction_belief_set_incompatible_pair', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 3, 5, 'drill_standard', 'BIP-05', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A protects inquiry broadly. Claim B forbids public examination of at least some ideas.', 'A. Society should protect free inquiry.', 'B. Dangerous ideas should never be examined publicly.', 'C. Inquiry often uncovers uncomfortable truths.', 'D. Public discourse can carry risk.'),
  ('philo-contradiction-bip-06', 'Contradiction Spotting: BIP-06', 'contradiction_belief_set_incompatible_pair', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 4, 6, 'drill_standard', 'BIP-06', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A connects responsibility to alternative possibilities. Claim B denies such alternatives by full determinism.', 'A. Responsibility requires the possibility of acting otherwise.', 'B. Every human action is fully determined by prior causes.', 'C. People are often praised and blamed.', 'D. Praise and blame assume responsibility.'),
  ('philo-contradiction-bip-07', 'Contradiction Spotting: BIP-07', 'contradiction_belief_set_incompatible_pair', 'Identify the strongest contradiction between labeled claims.', 'core', 'Select the two labels that are in strongest contradiction.', 10, 4, 6, 'drill_standard', 'BIP-07', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A says stable commitments contribute to the good life. Claim B says the best life avoids them altogether.', 'A. The good life includes stable commitments.', 'B. The best life avoids all commitments in order to remain maximally free.', 'C. Commitments can limit options.', 'D. Some limits may deepen life rather than reduce it.'),
  ('philo-contradiction-bip-08', 'Contradiction Spotting: BIP-08', 'contradiction_belief_set_incompatible_pair', 'Identify the strongest contradiction between labeled claims.', 'advanced', 'Select the two labels that are in strongest contradiction.', 10, 5, 7, 'drill_standard', 'BIP-08', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A defines equality as sameness. Claim B defines it as differential support based on need.', 'A. Equality requires giving everyone the same resources.', 'B. Equality sometimes requires giving more resources to those with greater need.', 'C. Need can affect what fairness requires.', 'D. Resource distribution shapes opportunity.'),
  ('philo-contradiction-bip-09', 'Contradiction Spotting: BIP-09', 'contradiction_belief_set_incompatible_pair', 'Identify the strongest contradiction between labeled claims.', 'advanced', 'Select the two labels that are in strongest contradiction.', 20, 5, 7, 'drill_higher_authoring', 'BIP-09', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A requires self-transcendence for meaning. Claim B says a purely self-contained project can still be fully meaningful.', 'A. Meaning in life must come from something beyond the self.', 'B. A self-created personal project can be fully meaningful even if it serves no one else.', 'C. People often pursue projects for their own sake.', 'D. Meaning can involve contribution or creation.'),
  ('philo-contradiction-bip-10', 'Contradiction Spotting: BIP-10', 'contradiction_belief_set_incompatible_pair', 'Identify the strongest contradiction between labeled claims.', 'advanced', 'Select the two labels that are in strongest contradiction.', 20, 6, 8, 'drill_higher_authoring', 'BIP-10', 'Which two claims are in strongest contradiction?', 'A', 'B', 'Claim A restricts moral worth entirely to intention. Claim B says outcomes also matter morally.', 'A. Moral worth depends only on intention.', 'B. Outcomes are morally relevant to evaluating an action.', 'C. Good intentions can still produce terrible results.', 'D. Moral evaluation may consider more than one thing.')
)
insert into public.quests_activities (
  slug,
  title,
  primary_skill_id,
  content_type,
  template_family,
  short_description,
  difficulty_label,
  completion_criteria,
  xp_reward,
  recommended_level_min,
  recommended_level_max,
  overlevel_grace_levels,
  round_content,
  repeatable,
  is_active
)
select
  authored_rounds.slug,
  authored_rounds.title,
  target_skill.id,
  'drill',
  authored_rounds.template_family,
  authored_rounds.short_description,
  authored_rounds.difficulty_label,
  authored_rounds.completion_criteria,
  authored_rounds.xp_reward,
  authored_rounds.recommended_level_min,
  authored_rounds.recommended_level_max,
  2,
  jsonb_build_object(
    'prompt_claims', array[
      authored_rounds.claim_a,
      authored_rounds.claim_b,
      authored_rounds.claim_c,
      authored_rounds.claim_d
    ],
    'question_text', authored_rounds.question_text,
    'correct_answer_labels', array[
      authored_rounds.correct_label_1,
      authored_rounds.correct_label_2
    ],
    'explanation', authored_rounds.explanation,
    'round_type', authored_rounds.round_type,
    'round_code', authored_rounds.round_code
  ),
  true,
  true
from authored_rounds
cross join target_skill
on conflict (slug) do update
set
  title = excluded.title,
  primary_skill_id = excluded.primary_skill_id,
  content_type = excluded.content_type,
  template_family = excluded.template_family,
  short_description = excluded.short_description,
  difficulty_label = excluded.difficulty_label,
  completion_criteria = excluded.completion_criteria,
  xp_reward = excluded.xp_reward,
  recommended_level_min = excluded.recommended_level_min,
  recommended_level_max = excluded.recommended_level_max,
  overlevel_grace_levels = excluded.overlevel_grace_levels,
  round_content = excluded.round_content,
  repeatable = excluded.repeatable,
  is_active = excluded.is_active,
  updated_at = now();
